apiVersion: v1
kind: Service
metadata:
  name: service-registry
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    component: {{ .Values.component.value }}
